# Carga de datos con distintos formatos

* Comma-Separated Values (CSV)
* JavaScript Object Notation (JSON)
* Microsoft Excel Spreadsheet (XLS)
Para mayor referencia, ver:
https://pandas.pydata.org/docs/user_guide/io.html

# Carga de datos con formato csv

Para ejemplificar este tema utilizaremos datos de la secretaría de salud:
https://coronavirus.gob.mx/
En el apartado de Datos y luego Descargas

O en la DGE que está la base de datos completa:
https://www.gob.mx/salud/documentos/datos-abiertos-152127

Usaremos el ejemplo de casos confirmados, de descargas de tipo csv y se descargó el archivo denominado
Casos_Diarios_Estado_Nacional_Confirmados_20211001.csv

In [2]:
#Hay varias formas de cargar este tipo de datos, como se puede ver, por ejemplo, en:
#https://empresas.blogthinkbig.com/python-5-formas-de-cargar-datos-csv-proyectos-machine-learning/
#Usaremos pandas
import pandas as pd

filename = 'https://raw.githubusercontent.com/claudianila/MiRepoCS/main/Data/Casos_Diarios_Estado_Nacional_Confirmados_20211001.csv'
data = pd.read_csv(filename, header=0) #header =0 indica que la primera línea es la que usaremos para los nombres de columnas

print(data.shape)
print (data.head(10))

(33, 565)
   cve_ent  poblacion               nombre  18-02-2020  19-02-2020  \
0        1    1434635       AGUASCALIENTES           0           0
1        2    3634868      BAJA CALIFORNIA           0           0
2        3     804708  BAJA CALIFORNIA SUR           0           0
3        4    1000617             CAMPECHE           0           0
4        7    5730367              CHIAPAS           0           0
5        8    3801487            CHIHUAHUA           0           0
6        9    9018645     DISTRITO FEDERAL           0           0
7        5    3218720             COAHUILA           0           0
8        6     785153               COLIMA           0           0
9       10    1868996              DURANGO           0           0

   20-02-2020  21-02-2020  22-02-2020  23-02-2020  24-02-2020  ...  \
0           0           0           0           0           0  ...
1           0           0           0           0           0  ...
2           0           0           0           0           0  ...
3           0           0           0           0           0  ...
4           0           0           0           0           0  ...
5           0           0           0           0           0  ...
6           0           0           0           0           1  ...
7           0           0           0           0           0  ...
8           0           0           0           0           0  ...
9           0           0           0           0           0  ...

   23-08-2021  24-08-2021  25-08-2021  26-08-2021  27-08-2021  28-08-2021  \
0         206         112         136         109         109          14
1         251         177         190         152         117          42
2         171         105         111         128          92          30
3         287         235         216         174         140          72
4         188         146         111         107          98          38
5          99          89          82          73          48          22
6        3232        3089        2760        2672        2394        1263
7         287         259         295         265         203          95
8         400         387         352         306         260         102
9         240         205         188         148         190          21

   29-08-2021  30-08-2021  31-08-2021  01-09-2021
0          27         121          21           0
1          32         142          70           0
2          25         101          50           1
3          48         117          31           0
4          39          69          29           0
5          13          57          24           0
6         426        2279        1423           5
7          68         238         147           1
8         128         233         194          10
9          27         143          74           0

[10 rows x 565 columns]

# Carga de datos en formato json
Para esta sección usaremos los datos del ejemplo del libro Data Wrangling de la editorial O'Reilly

In [5]:
json_data = pd.read_json('https://raw.githubusercontent.com/claudianila/MiRepoCS/main/Data/data-text.json')
json_data.head()

,Indicator,PUBLISH STATES,Year,WHO region,World Bank income group,Country,Sex,Display Value,Numeric,Low,High,Comments
0,Life expectancy at birth (years),Published,1990,Europe,High-income,Andorra,Both sexes,77,77,,,
1,Life expectancy at birth (years),Published,2000,Europe,High-income,Andorra,Both sexes,80,80,,,
2,Life expectancy at age 60 (years),Published,2012,Europe,High-income,Andorra,Female,28,28,,,
3,Life expectancy at age 60 (years),Published,2000,Europe,High-income,Andorra,Both sexes,23,23,,,
4,Life expectancy at birth (years),Published,2012,Eastern Mediterranean,High-income,United Arab Emirates,Female,78,78,,,

# Carga de datos con formato xlsx
En la siguiente liga se pueden descargar datos del inegi en formato xlsx

https://www.inegi.org.mx/app/tabulados/interactivos/?pxq=61a38ddd-3328-42e5-bd57-a3e18ab3cc62

Se descarga el archivo llamado:
Educacion_08.xlsx

In [1]:
#url='https://www.inegi.org.mx/app/tabulados/interactivos/?pxq=Educacion_Educacion_08_cc1ea8de-d7e1-445e-a33b-a88849155c78'
#data = pd.read_excel(url,header=0)
#data.head(10)

In [7]:

filename = 'https://raw.githubusercontent.com/claudianila/MiRepoCS/main/Data/Educacion_08.xlsx'
data = pd.read_excel(filename,header=0)

print(data.shape)
print (data.head(10))

(215, 8)
  Instituto Nacional de Estadística y Geografía (INEGI)       Unnamed: 1  \
0  Relación alumnos/maestro(escuela) por entidad ...                 NaN
1                                                NaN                 NaN
2                                 Entidad federativa     Nivel educativo
3                                 Entidad federativa     Nivel educativo
4                           Estados Unidos Mexicanos               Total
5                           Estados Unidos Mexicanos          Preescolar
6                           Estados Unidos Mexicanos            Primaria
7                           Estados Unidos Mexicanos          Secundaria
8                           Estados Unidos Mexicanos      Media superior
9                           Estados Unidos Mexicanos            Superior

         Unnamed: 2        Unnamed: 3        Unnamed: 4        Unnamed: 5  \
0               NaN               NaN               NaN               NaN
1               NaN               NaN               NaN               NaN
2         2010/2011         2010/2011         2015/2016         2015/2016
3  Alumnos/Maestros  Alumnos/Escuelas  Alumnos/Maestros  Alumnos/Escuelas
4                19               133                17               137
5                21                51                21                54
6                26               150                25               145
7                16               171                17               176
8                15               277                12               245
9                 9               474                 9               683

         Unnamed: 6        Unnamed: 7
0               NaN               NaN
1               NaN               NaN
2         2019/2020         2019/2020
3  Alumnos/Maestros  Alumnos/Escuelas
4                18               145
5                20                53
6                24               144
7                16               158
8                12               244
9                10               711

# Uso del archivo saltando renglones

In [1]:
#help(pd.read_excel)

In [9]:
#Este es un archivo que contiene la proporción de Alumnos-Maestros y Alumnos-Escuelas para diversos niveles educativos y Enticades
#Federativas
filename = 'https://raw.githubusercontent.com/claudianila/MiRepoCS/main/Data/Educacion_08.xlsx'
data = pd.read_excel(filename,header=0,skiprows=4)
#Renombramos las columnas
data.columns = ['Entidad Federativa','Nivel educativo','Alumnos/Maestros_2010/2011','Alumnos/Escuelas_2010/2011','Alumnos/Maestros_2015/2016','Alumnos/Escuelas_2015/2016','Alumnos/Maestros_2019/2020','Alumnos/Escuelas_2019/2020']

print(data.shape)
print (data.head(10))

(211, 8)
         Entidad Federativa Nivel educativo  Alumnos/Maestros_2010/2011  \
0  Estados Unidos Mexicanos           Total                        19.0
1  Estados Unidos Mexicanos      Preescolar                        21.0
2  Estados Unidos Mexicanos        Primaria                        26.0
3  Estados Unidos Mexicanos      Secundaria                        16.0
4  Estados Unidos Mexicanos  Media superior                        15.0
5  Estados Unidos Mexicanos        Superior                         9.0
6            Aguascalientes           Total                        17.0
7            Aguascalientes      Preescolar                        23.0
8            Aguascalientes        Primaria                        30.0
9            Aguascalientes      Secundaria                        13.0

   Alumnos/Escuelas_2010/2011  Alumnos/Maestros_2015/2016  \
0                       133.0                        17.0
1                        51.0                        21.0
2                       150.0                        25.0
3                       171.0                        17.0
4                       277.0                        12.0
5                       474.0                         9.0
6                       180.0                        16.0
7                        72.0                        24.0
8                       213.0                        31.0
9                       196.0                        14.0

   Alumnos/Escuelas_2015/2016  Alumnos/Maestros_2019/2020  \
0                       137.0                        18.0
1                        54.0                        20.0
2                       145.0                        24.0
3                       176.0                        16.0
4                       245.0                        12.0
5                       683.0                        10.0
6                       189.0                        17.0
7                        80.0                        24.0
8                       223.0                        32.0
9                       212.0                        14.0

   Alumnos/Escuelas_2019/2020
0                       145.0
1                        53.0
2                       144.0
3                       158.0
4                       244.0
5                       711.0
6                       191.0
7                        83.0
8                       226.0
9                       200.0

Archivo tomado sin leer los últimos renglones, que son los que traen 
elementos que no necesitamos

In [3]:
import pandas as pd

In [7]:
filename = 'https://raw.githubusercontent.com/claudianila/MiRepoCS/main/Data/Educacion_08.xlsx'
data = pd.read_excel(filename,header=0,skiprows=4,nrows=198)
#Renombramos las columnas
data.columns = ['Entidad Federativa','Nivel educativo','Alumnos/Maestros_2010/2011','Alumnos/Escuelas_2010/2011','Alumnos/Maestros_2015/2016','Alumnos/Escuelas_2015/2016','Alumnos/Maestros_2019/2020','Alumnos/Escuelas_2019/2020']

print(data.shape)
print (data.tail(10))

(198, 8)
    Entidad Federativa Nivel educativo  Alumnos/Maestros_2010/2011  \
188            Yucatán        Primaria                          27
189            Yucatán      Secundaria                          11
190            Yucatán  Media superior                          15
191            Yucatán        Superior                           9
192          Zacatecas           Total                          18
193          Zacatecas      Preescolar                          20
194          Zacatecas        Primaria                          23
195          Zacatecas      Secundaria                          14
196          Zacatecas  Media superior                          17
197          Zacatecas        Superior                           8

     Alumnos/Escuelas_2010/2011  Alumnos/Maestros_2015/2016  \
188                         179                          25
189                         165                          13
190                         298                          13
191                         357                          10
192                          86                          18
193                          40                          20
194                         101                          24
195                          72                          16
196                         286                          14
197                         342                          10

     Alumnos/Escuelas_2015/2016  Alumnos/Maestros_2019/2020  \
188                         165                          24
189                         181                          12
190                         195                          14
191                         528                          10
192                          94                          18
193                          44                          20
194                         105                          23
195                          83                          15
196                         223                          13
197                         650                          13

     Alumnos/Escuelas_2019/2020
188                         165
189                         163
190                         210
191                         583
192                          94
193                          43
194                         111
195                          76
196                         215
197                         651

In [4]:
help(pd.read_excel)

Help on function read_excel in module pandas.io.excel._base:

read_excel(io, sheet_name=0, header=0, names=None, index_col=None, usecols=None, squeeze=False, dtype=None, engine=None, converters=None, true_values=None, false_values=None, skiprows=None, nrows=None, na_values=None, keep_default_na=True, na_filter=True, verbose=False, parse_dates=False, date_parser=None, thousands=None, comment=None, skipfooter=0, convert_float=True, mangle_dupe_cols=True, storage_options: Union[Dict[str, Any], NoneType] = None)
    Read an Excel file into a pandas DataFrame.

    Supports `xls`, `xlsx`, `xlsm`, `xlsb`, `odf`, `ods` and `odt` file extensions
    read from a local filesystem or URL. Supports an option to read
    a single sheet or a list of sheets.

    Parameters
    ----------
    io : str, bytes, ExcelFile, xlrd.Book, path object, or file-like object
        Any valid string path is acceptable. The string could be a URL. Valid
        URL schemes include http, ftp, s3, and file. For file URLs, a host is
        expected. A local file could be: ``file://localhost/path/to/table.xlsx``.

        If you want to pass in a path object, pandas accepts any ``os.PathLike``.

        By file-like object, we refer to objects with a ``read()`` method,
        such as a file handle (e.g. via builtin ``open`` function)
        or ``StringIO``.
    sheet_name : str, int, list, or None, default 0
        Strings are used for sheet names. Integers are used in zero-indexed
        sheet positions. Lists of strings/integers are used to request
        multiple sheets. Specify None to get all sheets.

        Available cases:

        * Defaults to ``0``: 1st sheet as a `DataFrame`
        * ``1``: 2nd sheet as a `DataFrame`
        * ``"Sheet1"``: Load sheet with name "Sheet1"
        * ``[0, 1, "Sheet5"]``: Load first, second and sheet named "Sheet5"
          as a dict of `DataFrame`
        * None: All sheets.

    header : int, list of int, default 0
        Row (0-indexed) to use for the column labels of the parsed
        DataFrame. If a list of integers is passed those row positions will
        be combined into a ``MultiIndex``. Use None if there is no header.
    names : array-like, default None
        List of column names to use. If file contains no header row,
        then you should explicitly pass header=None.
    index_col : int, list of int, default None
        Column (0-indexed) to use as the row labels of the DataFrame.
        Pass None if there is no such column.  If a list is passed,
        those columns will be combined into a ``MultiIndex``.  If a
        subset of data is selected with ``usecols``, index_col
        is based on the subset.
    usecols : int, str, list-like, or callable default None
        * If None, then parse all columns.
        * If str, then indicates comma separated list of Excel column letters
          and column ranges (e.g. "A:E" or "A,C,E:F"). Ranges are inclusive of
          both sides.
        * If list of int, then indicates list of column numbers to be parsed.
        * If list of string, then indicates list of column names to be parsed.

          .. versionadded:: 0.24.0

        * If callable, then evaluate each column name against it and parse the
          column if the callable returns ``True``.

        Returns a subset of the columns according to behavior above.

          .. versionadded:: 0.24.0

    squeeze : bool, default False
        If the parsed data only contains one column then return a Series.
    dtype : Type name or dict of column -> type, default None
        Data type for data or columns. E.g. {'a': np.float64, 'b': np.int32}
        Use `object` to preserve data as stored in Excel and not interpret dtype.
        If converters are specified, they will be applied INSTEAD
        of dtype conversion.
    engine : str, default None
        If io is not a buffer or path, this must be set to identify io.
        Supported engines: "xlrd", "openpyxl", "odf", "pyxlsb".
        Engine compatibility :

        - "xlrd" supports old-style Excel files (.xls).
        - "openpyxl" supports newer Excel file formats.
        - "odf" supports OpenDocument file formats (.odf, .ods, .odt).
        - "pyxlsb" supports Binary Excel files.

        .. versionchanged:: 1.2.0
            The engine `xlrd <https://xlrd.readthedocs.io/en/latest/>`_
            now only supports old-style ``.xls`` files.
            When ``engine=None``, the following logic will be
            used to determine the engine:

           - If ``path_or_buffer`` is an OpenDocument format (.odf, .ods, .odt),
             then `odf <https://pypi.org/project/odfpy/>`_ will be used.
           - Otherwise if ``path_or_buffer`` is an xls format,
             ``xlrd`` will be used.
           - Otherwise if `openpyxl <https://pypi.org/project/openpyxl/>`_ is installed,
             then ``openpyxl`` will be used.
           - Otherwise if ``xlrd >= 2.0`` is installed, a ``ValueError`` will be raised.
           - Otherwise ``xlrd`` will be used and a ``FutureWarning`` will be raised. This
             case will raise a ``ValueError`` in a future version of pandas.

    converters : dict, default None
        Dict of functions for converting values in certain columns. Keys can
        either be integers or column labels, values are functions that take one
        input argument, the Excel cell content, and return the transformed
        content.
    true_values : list, default None
        Values to consider as True.
    false_values : list, default None
        Values to consider as False.
    skiprows : list-like, int, or callable, optional
        Line numbers to skip (0-indexed) or number of lines to skip (int) at the
        start of the file. If callable, the callable function will be evaluated
        against the row indices, returning True if the row should be skipped and
        False otherwise. An example of a valid callable argument would be ``lambda
        x: x in [0, 2]``.
    nrows : int, default None
        Number of rows to parse.
    na_values : scalar, str, list-like, or dict, default None
        Additional strings to recognize as NA/NaN. If dict passed, specific
        per-column NA values. By default the following values are interpreted
        as NaN: '', '#N/A', '#N/A N/A', '#NA', '-1.#IND', '-1.#QNAN', '-NaN', '-nan',
        '1.#IND', '1.#QNAN', '<NA>', 'N/A', 'NA', 'NULL', 'NaN', 'n/a',
        'nan', 'null'.
    keep_default_na : bool, default True
        Whether or not to include the default NaN values when parsing the data.
        Depending on whether `na_values` is passed in, the behavior is as follows:

        * If `keep_default_na` is True, and `na_values` are specified, `na_values`
          is appended to the default NaN values used for parsing.
        * If `keep_default_na` is True, and `na_values` are not specified, only
          the default NaN values are used for parsing.
        * If `keep_default_na` is False, and `na_values` are specified, only
          the NaN values specified `na_values` are used for parsing.
        * If `keep_default_na` is False, and `na_values` are not specified, no
          strings will be parsed as NaN.

        Note that if `na_filter` is passed in as False, the `keep_default_na` and
        `na_values` parameters will be ignored.
    na_filter : bool, default True
        Detect missing value markers (empty strings and the value of na_values). In
        data without any NAs, passing na_filter=False can improve the performance
        of reading a large file.
    verbose : bool, default False
        Indicate number of NA values placed in non-numeric columns.
    parse_dates : bool, list-like, or dict, default False
        The behavior is as follows:

        * bool. If True -> try parsing the index.
        * list of int or names. e.g. If [1, 2, 3] -> try parsing columns 1, 2, 3
          each as a separate date column.
        * list of lists. e.g.  If [[1, 3]] -> combine columns 1 and 3 and parse as
          a single date column.
        * dict, e.g. {'foo' : [1, 3]} -> parse columns 1, 3 as date and call
          result 'foo'

        If a column or index contains an unparseable date, the entire column or
        index will be returned unaltered as an object data type. If you don`t want to
        parse some cells as date just change their type in Excel to "Text".
        For non-standard datetime parsing, use ``pd.to_datetime`` after ``pd.read_excel``.

        Note: A fast-path exists for iso8601-formatted dates.
    date_parser : function, optional
        Function to use for converting a sequence of string columns to an array of
        datetime instances. The default uses ``dateutil.parser.parser`` to do the
        conversion. Pandas will try to call `date_parser` in three different ways,
        advancing to the next if an exception occurs: 1) Pass one or more arrays
        (as defined by `parse_dates`) as arguments; 2) concatenate (row-wise) the
        string values from the columns defined by `parse_dates` into a single array
        and pass that; and 3) call `date_parser` once for each row using one or
        more strings (corresponding to the columns defined by `parse_dates`) as
        arguments.
    thousands : str, default None
        Thousands separator for parsing string columns to numeric.  Note that
        this parameter is only necessary for columns stored as TEXT in Excel,
        any numeric columns will automatically be parsed, regardless of display
        format.
    comment : str, default None
        Comments out remainder of line. Pass a character or characters to this
        argument to indicate comments in the input file. Any data between the
        comment string and the end of the current line is ignored.
    skipfooter : int, default 0
        Rows at the end to skip (0-indexed).
    convert_float : bool, default True
        Convert integral floats to int (i.e., 1.0 --> 1). If False, all numeric
        data will be read in as floats: Excel stores all numbers as floats
        internally.
    mangle_dupe_cols : bool, default True
        Duplicate columns will be specified as 'X', 'X.1', ...'X.N', rather than
        'X'...'X'. Passing in False will cause data to be overwritten if there
        are duplicate names in the columns.
    storage_options : dict, optional
        Extra options that make sense for a particular storage connection, e.g.
        host, port, username, password, etc., if using a URL that will
        be parsed by ``fsspec``, e.g., starting "s3://", "gcs://". An error
        will be raised if providing this argument with a local path or
        a file-like buffer. See the fsspec and backend storage implementation
        docs for the set of allowed keys and values.

        .. versionadded:: 1.2.0

    Returns
    -------
    DataFrame or dict of DataFrames
        DataFrame from the passed in Excel file. See notes in sheet_name
        argument for more information on when a dict of DataFrames is returned.

    See Also
    --------
    DataFrame.to_excel : Write DataFrame to an Excel file.
    DataFrame.to_csv : Write DataFrame to a comma-separated values (csv) file.
    read_csv : Read a comma-separated values (csv) file into DataFrame.
    read_fwf : Read a table of fixed-width formatted lines into DataFrame.

    Examples
    --------
    The file can be read using the file name as string or an open file object:

    >>> pd.read_excel('tmp.xlsx', index_col=0)  # doctest: +SKIP
           Name  Value
    0   string1      1
    1   string2      2
    2  #Comment      3

    >>> pd.read_excel(open('tmp.xlsx', 'rb'),
    ...               sheet_name='Sheet3')  # doctest: +SKIP
       Unnamed: 0      Name  Value
    0           0   string1      1
    1           1   string2      2
    2           2  #Comment      3

    Index and header can be specified via the `index_col` and `header` arguments

    >>> pd.read_excel('tmp.xlsx', index_col=None, header=None)  # doctest: +SKIP
         0         1      2
    0  NaN      Name  Value
    1  0.0   string1      1
    2  1.0   string2      2
    3  2.0  #Comment      3

    Column types are inferred but can be explicitly specified

    >>> pd.read_excel('tmp.xlsx', index_col=0,
    ...               dtype={'Name': str, 'Value': float})  # doctest: +SKIP
           Name  Value
    0   string1    1.0
    1   string2    2.0
    2  #Comment    3.0

    True, False, and NA values, and thousands separators have defaults,
    but can be explicitly specified, too. Supply the values you would like
    as strings or lists of strings!

    >>> pd.read_excel('tmp.xlsx', index_col=0,
    ...               na_values=['string1', 'string2'])  # doctest: +SKIP
           Name  Value
    0       NaN      1
    1       NaN      2
    2  #Comment      3

    Comment lines in the excel input file can be skipped using the `comment` kwarg

    >>> pd.read_excel('tmp.xlsx', index_col=0, comment='#')  # doctest: +SKIP
          Name  Value
    0  string1    1.0
    1  string2    2.0
    2     None    NaN